# Generated by Django 3.1 on 2020-08-26 05:12

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('date_deadline', models.DateTimeField(default=api.models.default_date_deadline)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('date_completed', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pact')),
            ],
        ),
    ]
