# Generated by Django 3.1 on 2020-08-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='pact',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
