# Generated by Django 3.1 on 2020-08-26 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200826_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pact',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pact',
            name='verifier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='verifier', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pact',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
